[package]
name = "generate_golden_vectors"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zpx_router = { path = "../../programs/zpx_router" }
