[workspace]
members = ["programs/zpx_router", "programs/zpx_lp_vaults"]

[programs.localnet]
universal_router_sol = "zoopxFVyJcE2LAcMqDnKjWx9jv7UWDkDvqviVVypVPz"

[programs.devnet]
# placeholder for devnet program id if you deploy to devnet
universal_router_sol = "zoopxFVyJcE2LAcMqDnKjWx9jv7UWDkDvqviVVypVPz"

[registry]
# Build artifacts path (Anchor default) - can be adjusted in CI
idl = "target/idl"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[build]
# Rust configuration; ensure SBF target is pinned in CI
rust = "stable"
