[workspace]
members = [
	"programs/zpx_router",
	"programs/zpx_lp_vaults",
	"tools/generate_golden_vectors",
]
resolver = "2"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "abort"
incremental = false
strip = "symbols"
