[workspace]
members = [
	"programs/zpx_router",
	"programs/zpx_adapter",
	"programs/zpx_adapter_cctp_v1",
	"programs/zpx_adapter_cctp_v2",
	"programs/zpx_lp_vaults",
]
resolver = "2"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "abort"
incremental = false
