[package]
name = "zpx_router"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
name = "zpx_router"
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"
solana-program = "1.14.16"

[features]
default = []
