name: ci
on: [push, pull_request]
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy (deny warnings)
        run: cargo clippy --all-targets -- -D warnings
      - name: Unit tests
        run: cargo test -p zoopx-router --lib --tests --verbose
      - name: Integration tests (program-test)
        run: cargo test -p zoopx-router --test router_pt -- --nocapture
