name: Supply Chain & Dependency Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  supply-chain-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.80.0
      - name: Install cargo-audit and cargo-deny
        run: |
          rustup default stable
          cargo install cargo-audit || true
          cargo install cargo-deny || true
      - name: Run cargo-audit
        run: |
          cargo audit || true
      - name: Run cargo-deny
        run: |
          cargo deny check || true
